const routers = [
    {path: '/',component: (resolve) => require(['../views/index.vue'], resolve)},
    {path: '/login',component: (resolve) => require(['../views/login.vue'], resolve)},
    {path: '/school',component: (resolve) => require(['../views/school/index.vue'], resolve)},
    {path: '/school/add',component: (resolve) => require(['../views/school/model.vue'], resolve)},
    {path: '/school/update',component: (resolve) => require(['../views/school/model.vue'], resolve)},
    {path: '/grade',component: (resolve) => require(['../views/grade/index.vue'], resolve)},
    {path: '/grade/add',component: (resolve) => require(['../views/grade/model.vue'], resolve)},
    {path: '/grade/update',component: (resolve) => require(['../views/grade/model.vue'], resolve)},
    {path: '/class',component: (resolve) => require(['../views/class/index.vue'], resolve)},
    {path: '/class/update',component: (resolve) => require(['../views/class/model.vue'], resolve)},
    {path: '/class/import',component: (resolve) => require(['../views/class/import.vue'], resolve)},
    {path: '/class_move',component: (resolve) => require(['../views/class_move/index.vue'], resolve)},
    {path: '/class_move/update',component: (resolve) => require(['../views/class_move/model.vue'], resolve)},
    {path: '/class_move/import',component: (resolve) => require(['../views/class_move/import.vue'], resolve)},
    {path: '/course',component: (resolve) => require(['../views/course/index.vue'], resolve)},
    {path: '/course/update',component: (resolve) => require(['../views/course/model.vue'], resolve)},
    {path: '/course/import',component: (resolve) => require(['../views/course/import.vue'], resolve)},
    {path: '/room',component: (resolve) => require(['../views/room/index.vue'], resolve)},
    {path: '/room/update',component: (resolve) => require(['../views/room/model.vue'], resolve)},
    {path: '/room/import',component: (resolve) => require(['../views/room/import.vue'], resolve)},
    {path: '/teacher',component: (resolve) => require(['../views/teacher/index.vue'], resolve)},
    {path: '/teacher/update',component: (resolve) => require(['../views/teacher/model.vue'], resolve)},
    {path: '/teacher/import',component: (resolve) => require(['../views/teacher/import.vue'], resolve)},
    {path: '/student',component: (resolve) => require(['../views/student/index.vue'], resolve)},
    {path: '/student/update',component: (resolve) => require(['../views/student/model.vue'], resolve)},
    {path: '/student/import',component: (resolve) => require(['../views/student/import.vue'], resolve)},
    {path: '/score_import',component: (resolve) => require(['../views/score_import/index.vue'], resolve)},
    {path: '/score_import/view',component: (resolve) => require(['../views/score_import/model.vue'], resolve)},
    {path: '/score_import/import',component: (resolve) => require(['../views/score_import/import.vue'], resolve)},
    {path: '/role',component: (resolve) => require(['../views/role/index.vue'], resolve)},
    {path: '/role/add',component: (resolve) => require(['../views/role/model.vue'], resolve)},
    {path: '/role/update',component: (resolve) => require(['../views/role/model.vue'], resolve)},
    {path: '/func',component: (resolve) => require(['../views/func/index.vue'], resolve)},
    {path: '/func/update',component: (resolve) => require(['../views/func/model.vue'], resolve)}
];

export default routers;